name: meww
version: 0.0.1
synopsis: feline wacky widget system 
description: widget scripting system
maintainer: Shekhinah Memmel <she@khinah.xyz>
github: herkhinah/meww
category: Development
language: GHC2021

dependencies:
  - base
  - megaparsec
  # widgets == 0.1.0
  - containers
  - transformers
  - lens
  - ghc
  - HUnit
  
default-extensions:
  - OverloadedRecordDot
  - DuplicateRecordFields
  - LambdaCase
  - PatternSynonyms

executable:
  main: Main.hs
  source-dirs: 
    - app

executable:
  main: Test.hs
  source-dirs:
    - app
    - tests