name:                meww
version:             0.1.0.0
github:              "githubuser/meww"
license:             BSD3
author:              "Shekhinah Memmel"
maintainer:          "she@khinah.xyz"
copyright:           "AGPLv3"
language:            GHC2021

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/meww#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- parser-combinators
- containers
- transformers
- lens
- ghc == 9.2.8
- HUnit
- semigroupoids
- adjunctions
- record-hasfield
- text

default-extensions:
  - OverloadedRecordDot
  - DuplicateRecordFields
  - LambdaCase
  - PatternSynonyms

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints


library:
  source-dirs: src

executables:
  meww-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meww

tests:
  meww-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - meww
