name: meww
version: 0.0.1
synopsis: feline wacky widget system 
description: widget scripting system
maintainer: Shekhinah Memmel <she@khinah.xyz>
github: herkhinah/meww
category: Development
language: GHC2021

dependencies:
  - base ^>=4.15
  - megaparsec >= 9.2.2
  - widgets == 0.1.0
  - containers >= 0.6
  - transformers >= 0.5
  
default-extensions:
  - DuplicateRecordFields

executable:
  main: Main.hs
  source-dirs: app